name: Setup microk8s
description: sets up OS packages, helm lint and testing environment for linstor
inputs:
  create-microk8s-cluster:  # id of input
    description: 'Whether or not to create a microk8s cluster during setup'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3.5
      with:
        version: v3.9.0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - uses: balchua/microk8s-actions@v0.4.1
      with:
        channel: '1.28/stable'
        addons: '["dns", "rbac", "registry"]'

    - name: Add Dependencies
      shell: bash
      run: |
        helm repo add dtrdnk-helm-charts https://dtrdnk.github.io/helm-charts
        helm repo add jetstack https://charts.jetstack.io
