{{- range .Values.linstorSatelliteConfiguration }}
{{- $internalTLS := include "linstor-cluster.internalTLS" $ }}
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: {{ .name }}
  labels:
    {{- include "linstor-cluster.labels" $ | nindent 4 }}
spec:
  {{- if $internalTLS }}
  internalTLS:
  {{- $internalTLS | nindent 4 }}
  {{- end }}
  {{- with (dig "nodeSelector" (dict) .) }}
  nodeSelector: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "storagePools" (dict) .) }}
  storagePools: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "patches" (dict) .) }}
  patches: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (dig "properties" (dict) .) }}
  properties: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
