---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "tempo-operator.labels" . | nindent 4 }}
  name: {{ include "tempo-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tempo-operator.fullname" . }}-leader-election
subjects:
  - kind: ServiceAccount
    name: {{ include "tempo-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
