apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "tempo-operator.labels" . | nindent 4 }}
  name: {{ include "tempo-operator.fullname" . }}-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tempo-operator.fullname" . }}-proxy
subjects:
  - kind: ServiceAccount
    name: {{ include "tempo-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
