apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "tempo-operator.labels" . | nindent 4 }}
  name: {{ include "tempo-operator.fullname" . }}-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "tempo-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "tempo-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.{{ .Values.clusterName }}
  issuerRef:
    kind: Issuer
    name: {{ include "tempo-operator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
