apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo-operator.fullname" . }}-webhook
  labels:
    {{- include "tempo-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.webhook.port}}
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "tempo-operator.selectorLabels" . | nindent 4 }}
