name: Setup kind
description: sets up helm lint and testing environment
inputs:
  create-kind-cluster:  # id of input
    description: 'Whether or not to create a kind cluster during setup'
    required: true
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v3.5
      with:
        version: v3.9.0

    - uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Set up chart-testing
      uses: helm/chart-testing-action@v2.6.1

    - name: Create kind cluster
      uses: helm/kind-action@v1.8.0
      if: ${{ inputs.create-kind-cluster == 'true' }}
      with:
        node_image: kindest/node:v1.28.0

    - name: Add Dependencies
      shell: bash
      run: |
        helm repo add dtrdnk-helm-charts https://dtrdnk.github.io/helm-charts
        helm repo add jetstack https://charts.jetstack.io
