name: Test Piraeus Chart

on:
  pull_request:
    paths:
      - 'charts/piraeus/**'
    branches:
      - master
  push:
    paths:
      - 'charts/piraeus/**'
    branches:
      - master

jobs:
  piraeus-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup kind
        uses: ./.github/actions/setup-kind
        with:
          create-kind-cluster: "true"

      - name: Run chart-testing (install)
        run: ct install --charts charts/piraeus
