linstorCluster:
  apiTLS:
    certManager:
      name: api-issuer
      kind: Issuer
    apiSecretName: linstor-api-tls
    clientSecretName: linstor-client-tls
    csiControllerSecretName: linstor-csi-controller-tls
    csiNodeSecretName: linstor-csi-node-tls
  internalTLS:
    certManager:
      name: internal-issuer
      kind: Issuer
    secretName: internal-tls
